import { Canvas } from '@react-three/fiber'
import Head from 'next/head'
import { Suspense, useContext } from 'react'
import { CanvasSetupContext } from 'store/canvasSetup/CanvasSetupProvider'
import MainScene from 'components/MainScene/MainScene'
import { useContextBridge } from '@react-three/drei'

export default function Home() {
    const { width, height, cameraZoom } = useContext(CanvasSetupContext)

    const ContextBridge = useContextBridge(CanvasSetupContext)

    const dpr = typeof window !== 'undefined' ? window.devicePixelRatio : 1

    return (
        <main>
            <Head>
                <title>Next.js + R3F Shader Lab</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Canvas
                style={{ width: width, height: height }}
                orthographic
                dpr={dpr}
                camera={{ position: [0, 0, 5], zoom: cameraZoom }}
                gl={{ preserveDrawingBuffer: true }}
            >
                <ContextBridge>
                    <Suspense fallback={null}>
                        <MainScene />
                    </Suspense>
                </ContextBridge>
            </Canvas>
        </main>
    )
}
